[env]
TERM = "xterm-256color"
[window]
padding.x = 20
padding.y = 20

decorations = "none"

opacity = 0.5
blur = false

option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

size = 18.0



[colors]
[colors.primary]
background = "0x303446"
foreground = "0xc6d0f5"

[colors.cursor]
text = "0x303446"
cursor = "0xc6d0f5"

[colors.normal]
black = "0x303446"
red = "0xe78284"
green = "0xa6d189"
yellow = "0xe5c890"
blue = "0x8caaee"
magenta = "0xea999c"
cyan = "0x81c8be"
white = "0xc6d0f5"

[colors.bright]
black = "0x626880"
red = "0xe78284"
green = "0xa6d189"
yellow = "0xe5c890"
blue = "0x8caaee"
magenta = "0xea999c"
cyan = "0x81c8be"
white = "0xa5adcb"


